title: "BOTONG XUE"
description: "Botong can be reached at"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: yes            # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a gray header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: PULICATIONS}
  - {title: TEACHING EXPERIENCE}


external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:xuebotong@gmail.com"}
  - {title: linkedin, icon: linkedin, url: "http://linkedin.com/in/botong-xue-517071126"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
